### ISSUE TITLE
Add relation type that allows linking to a changelog

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/version#6]
Idea from https://github.com/linz/stac/issues/183

Linking to a changelog seems to be something that is useful and in the scope of this extension.
So adding a rel type for changelogs might be they way to go.

**Comment by m-mohr** [comment]
The IANA relation type for this would probably be `version-history`, see https://www.rfc-editor.org/rfc/rfc5829.html#section-3.1

**Comment by l0b0** [comment]
Wouldn't this mean linking to non-STAC files in the `links` section? That seems like it could be quite a problem for anyone trying to traverse the dataset. Also, "changelog" is IMO not a "relation", it's more of a file type.

**Comment by m-mohr** [comment]
Yes, I was thinking more about an external non-STAC file. IMHO `version-history` is a good relation, I think. Because then you can still - via media types - provide multiple different file formats, e.g. one that is JSON and machine-readable and potentially somewhat compliant with STAC and one that is e.g. a markdown file (like the keepachangelog.com ones) or an HTML one.
