### ISSUE TITLE
Multiple latest, predecessors, and/or successors

### ISSUE THREAD

**Issue by schwehr** [stac-extensions/version#7]
My attempt to answer the question of: "Can an asset have more than one successor or more than one predecessor?"

Summary: It looks like have multiple links of a specific version `rel` in one STAC thing is fine.  Anyone have a take that is contrary to that?

There are cases where a new STAC Item or Collection is a merge of multiple predecessors and is split into multiple successors.

First, does [RFC 5829](https://datatracker.ietf.org/doc/html/rfc5829) "Link Relation Types for Simple Version Navigation between Web Resources" apply?  I believe the answer is only a little bit.  I think the intent was to use the same names, but not necessarily all of the semantics.  That doc does say:

> 2.  Terminology
>
> [SNIP]
>
>   Predecessor, Successor
>
>      When a versioned resource is checked out and then subsequently
>      checked in, the version that was checked out becomes a
>      "predecessor" of the version created by the checkin.  A client can
>      specify multiple predecessors for a new version if the new version
>      is logically a merge of those predecessors.  The inverse of the
>      predecessor relation is the "successor" relation.  Therefore, if X
>      is a predecessor of Y, then Y is a successor of X.

and

> 3.6.  'successor-version'
>
> When included on a versioned resource, this link points to a resource
>   containing the successor version in the version history.
>
>   Some systems may allow more than one of these link relations in order
>   to support branching.

The schema doesn't have links in it, so it offers us no guidance.  https://github.com/stac-extensions/version/blob/a39e9247b90c1ce3e3908bfb616c1d4807387614/json-schema/schema.json

Reading https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#link-object, I don't see anything that limits it to just one link of a type.

And https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#using-relation-types and https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#versioning-for-catalogs don't give any indication that it can only be one

https://www.iana.org/assignments/link-relations/link-relations.xhtml just points back to RFC5829

**Comment by m-mohr** [comment]
I didn't think about this when writing this extension. I'd say multiple latest-version links would be not very logical, but otherwise, there's no restriction.
